services:
  pg_gembed:
    build:
      context: .
    container_name: pg_gembed_container
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    depends_on:
      - grpc_server
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      GRPC_EMBEDDER_ENDPOINT: http://grpc_embedder_container:50051

  grpc_server:
    build:
      context: ./gembed/server
    container_name: grpc_embedder_container
    ports:
      - "50051:50051"

volumes:
  pg_data:
